### ISSUE TITLE
How to register in ur new update?

### ISSUE THREAD

**Issue by violent-silentium** [Assertrex/BronyCenter#1]
How to make admin account?

**Comment by Assertrex** [comment]
Huh... Wow... I haven't thought that I will get any answer about the project. Well, I have no experience with making something open-source and it's the biggest project I've ever made. It's still not finished, I still have to write registration method and moderation panel for example. I don't know if you already have an account (if you had before, some things can break after update), but if not:

Registration:

Table users -> add:
    display_name ( any characters allowed after update ),
    username ( only alphanumeric characters ),
    email,
    password ( password_hash($newPassword, PASSWORD_BCRYPT, ['cost' => 13]) )
registration_ip.
    registration_datetime ( MySQL format, for example: 2018-01-06 14:42:00 ),
    country_code ( for example RU, but optional ),
    account_type ( 0 - email unverified, 1 - standard user, 8 - moderator, 9 - administrator )
Table users_details and users_statistics (you need to create a row with user_id same as your id in users table.
Anyway, I don't recommend to use this code, as it's not finished shit XD I upload it on GitHub to see changes in Atom and to remotely see source code.

On 06.01.2018 14:27:16, Sify Firewings <notifications@github.com> wrote:
How to make admin account?

**Comment by violent-silentium** [comment]
Thank you, in fact, I didn't know only the password encryption method.
Could you answer my recent message in the email?
